# Context must be `Apyllon/`
FROM python:3.7-alpine

LABEL Description="Apyllon - dev edition"
LABEL Version="0.0.1"

WORKDIR /home/backend

COPY requirements.txt requirements.txt

RUN apk add --update && \
    apk add --no-cache \
    gcc \
    g++ \
    musl-dev \
    linux-headers \
    postgresql-dev \
    openssl \
    libffi-dev \
    taglib-dev && \
    python3 -m venv venv && \
    venv/bin/pip3 install --upgrade pip && \
    venv/bin/pip3 install -r requirements.txt

COPY \
    "logger.ini" \
    "apyllon.py" \
    "config.py" \
    "docker/boot_backend.sh" \
    "./"
COPY backend backend
COPY migrations migrations

RUN adduser -D backend && \
    mkdir -p /certificates && \
    chown -R backend: /home/backend && \
    chown -R backend: /certificates && \
    chmod +x boot_backend.sh

USER backend

ENV FLASK_APP apyllon.py

EXPOSE 5000
