# Context must be `Apyllon/`
FROM python:3.7-stretch

LABEL Description="Apyllon - dev edition"
LABEL Version="0.0.1"

WORKDIR /home/backend

COPY requirements.txt requirements.txt

RUN dpkg --configure -a && \
    apt-get update && \
    apt-get --yes  install  \
    postgresql \
    postgresql-client \
    openssl \
    vlc-nox \
    libtag1-dev 


RUN python -m venv venv && \
    venv/bin/pip3 install --upgrade pip && \
    venv/bin/pip3 install -r requirements.txt

COPY \
    "logger.ini" \
    "apyllon.py" \
    "config.py" \
    "docker/boot_backend.sh" \
    "./"

COPY backend backend

COPY migrations migrations

RUN useradd -ms /bin/bash backend

RUN mkdir -p /certificates && \
    chown -R  backend: /home/backend && \
    chown -R  backend: /certificates && \
    chmod +x  boot_backend.sh

USER backend

ENV FLASK_APP apyllon.py

USER backend

EXPOSE 5000
