"""Add album to Song

Revision ID: 3d7db9e741ca
Revises: 65f518f5eea2
Create Date: 2018-10-17 14:11:31.241581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d7db9e741ca'
down_revision = '65f518f5eea2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('album', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('song', 'album')
    # ### end Alembic commands ###
